---
name: Checks # this is the name as it's going to appear in Github actions.

on: [push] # this is the trigger. we are saying we want this particular actions to run on push 

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # runs-on is the runner that we're going to be running our job on.
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # uses allows you to use another pre-made action that's provided in the GitHub actions repository.
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout # it checks our code out inside our Github actions job
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"